steps:
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/bbc/connected-data-bristlecone']
  - name: 'gcr.io/cloud-builders/docker'
    args: ["build", "-t", "gcr.io/$PROJECT_ID/rubus:$REVISION_ID", "-f", "Dockerfile", "."]
images:
  - "gcr.io/$PROJECT_ID/bristlecone:$REVISION_ID"
